### PR TITLE
fix: Add custom symbols_path in iOS symbol map discovery

### LINKED ISSUE #392: iOS dart-symbol-map upload does not use symbols_path for dSYM discovery
### Environment

sentry-dart-plugin: latest (main branch)
Flutter: 3.29.3
Platform: iOS

### Steps to Reproduce

1. Configure the plugin with symbols_path pointing to a custom directory (outside the default Flutter build/ tree) that contains App.framework.dSYM and obfuscation_map.json
2. Configure dart_symbol_map_path pointing to the obfuscation map
3. Run the plugin

This is common in CI setups where symbols are downloaded from external storage (e.g., S3) to a separate directory rather than being in the Flutter project's build output.

### Expected Result

The plugin should find App.framework.dSYM/Contents/Resources/DWARF/App inside the symbols_path directory, pair it with the obfuscation map, and upload via sentry-cli dart-symbol-map upload. Dart exception types and values should be deobfuscated in Sentry.

### Actual Result

The plugin reports success but Dart names remain obfuscated (e.g., exception type aig instead of the real class name).

The iOS dSYM discovery in collectDebugFilesForDartMap only searches {buildFilesFolder}/ios/ and {projectRoot}/ios/build/. It does not check symbolsFolder (symbols_path), even though Android symbol collection does use it.

Because no iOS debug files are found, the dart symbol map upload is silently skipped, and the plugin still exits successfully.

Running sentry-cli dart-symbol-map upload manually with the same files works correctly.

### PR DESCRIPTION
**Pull request by denrase**
## :scroll: Description

Flutter produces debug files differently on each platform:
 - Android writes app.android-*.symbols into the configured --split-debug-info / symbols_path directory.
 - iOS keeps App.framework.dSYM/.../App in standard build output paths such as build/ios/...; symbols_path is only relevant there when artifacts have been moved or downloaded in CI.

Update discovery accordingly:
 - Android: Only search the configured symbol directory.
 - iOS: Search both the configured symbol directory and the standard iOS build roots.

## :bulb: Motivation and Context

Closes #392

## :green_heart: How did you test it?

Unit tests. Checked where ios/android apps put the files.

## :pencil: Checklist

- [x] I reviewed submitted code
- [x] I added tests to verify changes
- [ ] I updated the docs if needed
- [x] All tests passing
- [x] No breaking changes

### CODE REVIEW

File: lib/src/symbol_maps/dart_symbol_map_debug_files_collector.dart [hunk 1]
```diff
@@ -43,25 +47,24 @@ Future<Set<String>> collectDebugFilesForDartMap({
...
   }
 
-  // Prefer scanning Android symbols under the configured symbols folder; if not
-  // set, fall back to the build folder.
+  // Android Dart symbol files are written to the configured split-debug-info
+  // directory (symbolsFolder).
   final List<String> androidRoots = <String>[];
   if (config.symbolsFolder.isNotEmpty) {
-    androidRoots.add(path.normalize(config.symbolsFolder));
-  } else if (config.buildFilesFolder.isNotEmpty) {
```
Comment (denrase) [inline lib/src/symbol_maps/dart_symbol_map_debug_files_collector.dart:51]: @buenaflor The `else if (config.buildFilesFolder.isNotEmpty)` was probably dead code, as the `symbolsFolder` has `.` as fallback, so it would have never been empty in the first place.

**Comment by buenaflor** [comment]
@denrase did you verify the behaviour by reproducing the issue steps?

File: lib/src/symbol_maps/dart_symbol_map_debug_files_collector.dart [hunk 2]
```diff
@@ -43,25 +47,24 @@ Future<Set<String>> collectDebugFilesForDartMap({
     }
   }
 
-  // Prefer scanning Android symbols under the configured symbols folder; if not
-  // set, fall back to the build folder.
+  // Android Dart symbol files are written to the configured split-debug-info
+  // directory (symbolsFolder).
```
Comment (buenaflor) [inline lib/src/symbol_maps/dart_symbol_map_debug_files_collector.dart:52]: pls also add that symbolsFolder falls back to scanning the root (`.`)

I think it's easy to miss that detail

Comment (denrase) [reply lib/src/symbol_maps/dart_symbol_map_debug_files_collector.dart:52]: we do this in config now

**Review by buenaflor — APPROVED** [review]
lgtm 👍 pls fix failing tests
